version: '3.8'

services:
  fhir-service:
    image: ${DC_IMAGE:-ghcr.io/d-tree-org/fhir-helper-service:v0.0.3}
    ports:
      - ${PORT}:4040
    environment:
      - TZ:"Africa/Blantyre"
      - KEYCLOAK_ID:${KEYCLOAK_ID}
      - KEYCLOAK_SECRET:${KEYCLOAK_SECRET}
      - KEYCLOAK_ISSUER:${KEYCLOAK_ISSUER}
      - KEYCLOAK_AUTHORIZE_TOKEN_URL:${KEYCLOAK_AUTHORIZE_TOKEN_URL}
      - KEYCLOAK_ACCESS_TOKEN_URL:${KEYCLOAK_ACCESS_TOKEN_URL}
      - KEYCLOAK_USERNAME:${KEYCLOAK_USERNAME}
      - KEYCLOAK_PASSWORD:${KEYCLOAK_PASSWORD}
      - FHIR_BASE_URL:${FHIR_BASE_URL}
      - RESOURCES_CACHE_DIR=${RESOURCES_CACHE_DIR}
      - RESOURCES_CACHE_TAG=${RESOURCES_CACHE_TAG}
      - RESOURCES_CACHE_URL=${RESOURCES_CACHE_URL}
      - RESOURCES_SSH_PASSPHRASE=${RESOURCES_SSH_PASSPHRASE}
      - RESOURCES_SSH_LOCATION=${RESOURCES_SSH_LOCATION}
      - RESOURCES_GIT_KEY=${RESOURCES_GIT_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - fhir_data:/data